[package]
name = "k8056"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Code to controll the k8056 relay card"
docmentation = "N/A"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
